study {
    name = "LNVG ET3 + ET3 + ET6"
    description = "Reference characterization using nominal parameters"
}

trainModel {
    provider = "lnvg"

    settings {
        weight_kg = 650_000
        maxSpeed_kph = 160
        acceleration_mps2 = 1
        retardation = 0.95
        motorAdhesion_pu = 0.25
        motorBrakeAdhesion_pu = 0.18
        brakeAdhesion_pu = 0.13
        motorPerformance_pu = 1
        brakePerformance_pu = 1
   }

    controller {
       vehicles = ["ET4", "ET4", "ET6"]
    }

    plots {
      traction = true
      braking = true
      efficiency = true
      fuel = false
      }
}